name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  hello-world:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello world
        run: echo "Hello World!"
  
  dagger-hello-world:
    name: Dagger Hello World
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Call Dagger Hello World
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.11.1"
          verb: call
          module: dagger
          args: hello
