name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check-go-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.1'

      - run: go version
  
  check-go-version2:
    runs-on: ubuntu-latest
    needs: check-go-version

    steps:
      - name: Check Go version
        run: go version
